### ISSUE TITLE
Main content of sponsors page is blocked by some ad blockers

### ISSUE THREAD

**Issue by Hexstream** [ultralisp/ultralisp#86] opened 2020-09-10 18:17 UTC
The [Ultralisp sponsors page](https://ultralisp.org/sponsors) remains essentially blank for me no matter what I do, [as I reported almost 2 weeks ago](https://github.com/ultralisp/ultralisp/commit/dc96d949d6dc1ee7acf0fa910e7ccb18eee0211b#commitcomment-41881261).

Sorry for not creating a formal issue earlier, but I expected this would be quickly resolved.

I realize this may not affect everyone, but this seems like a dangerous issue which should be tracked down. Do you really want some people to have a completely different view of your site without you or them even knowing?

**Comment by svetlyak40wt** [comment] 2020-09-10 18:30
Hmm, this page is "static" and shouldn't be different for different users. Also, I've restarted the server few times since that release and Weblocks only caches in the process memory.

Here is what I see in my main Chromium based browser (where I'm logged in):

<img width="748" alt="Screenshot 2020-09-10 at 21 23 56" src="https://user-images.githubusercontent.com/24827/92780921-55f0f280-f3ac-11ea-91d1-5481697fdf6c.png">

Here is what I see as anonymous in Safari:

<img width="770" alt="Screenshot 2020-09-10 at 21 27 29" src="https://user-images.githubusercontent.com/24827/92781157-8c2e7200-f3ac-11ea-9f5e-a242de09eb26.png">

And the same result in console with CURL:

```
[art@art-2osx:~]% curl -s 'https://ultralisp.org/sponsors' | grep -A 7 'Grand Supporters'
  <h2>Grand Supporters</h2>
  <ul>
   <li><a href=https://www.hexstreamsoft.com>Jean-Philippe Paradis</a>
   <li><a href=https://blackbrane.com>Black Brane Systems Inc.</a>
  </ul>
  <p>
   To get listed on this page, become a "gold" or "grand" sponsor on <a
   href="https://www.patreon.com/ultralisp">Patreon</a> or <a
```

Probably, there is some issue with HTML rendering.

Could you please attach a screenshot and the full HTML source of the page?

**Comment by Hexstream** [comment] 2020-09-10 19:14
This appears to be a compatibility issue between Adblock and Yandex.Metrika.

If I disable Adblock or whitelist ultralisp.org, the page works correctly.

Could you try moving the Yandex.Metrika stuff to the bottom of the page to see if this allows the page to render correctly?

**Comment by svetlyak40wt** [comment] 2020-09-11 06:59
I've installed "adguard.com" blocker and was able to reproduce the problem.

Removed Yandex Metrica and Google Analytics from the page but this didn't help. Seems Adguard removes part of the page using some internal rules.

Will try to figure out why it decides to remove these HTML nodes.

**Comment by svetlyak40wt** [comment] 2020-09-11 07:09
Oh, the problem was in the HTML class.

Fixed in https://github.com/ultralisp/ultralisp/commit/a5b31efe8137936545933027e802d5f95468e5e6

**Comment by svetlyak40wt** [comment] 2020-09-11 07:11
Please, note right now, I've hot-fixed this on the fly (thanks to the Common Lisp). If server will restart for some reason, the fix will disappear.

The fix will become persistent with the next release, probably tomorrow.

**Comment by Hexstream** [comment] 2020-09-11 11:25
Ah, this fixes it! Thank you. That was kind of a weird progression of bug theories...

**Comment by Hexstream** [comment] 2020-10-03 16:51
Somehow this issue has resurfaced.

**Comment by svetlyak40wt** [comment] 2020-10-03 20:35
Seems, I didn't build a new docker image for production and server reloaded at some moment. One of the cons of the image-driven development flow.

**Comment by Hexstream** [comment] 2020-10-06 12:15
Building a new docker image for production is an excessively involved process, I guess?

It's pretty rare that restarting a server *causes* problems rather than *solving* them.

Can you at least reopen this issue until this is actually solved?

I'm throwing tons of cash at you and honestly, this is a very grating issue.

**Comment by svetlyak40wt** [comment] 2020-10-08 23:02
Now it is fixed permanently.

**Closed by svetlyak40wt** 2020-10-08 23:02 UTC

**Comment by Hexstream** [comment] 2020-10-08 23:07
Thank you! Now I can finally sleep at night! 😂
