### ISSUE TITLE
Importing GitHub projects requests write access

### ISSUE THREAD

**Issue by eschulte** [ultralisp/ultralisp#66] opened 2020-02-03 13:14 UTC
When I click through to allow ultralisp to import my public GitHub projects, it requests write access to the code of my public repositories. This seems excessive and unnecessary, or am I missing something?

**Comment by svetlyak40wt** [comment] 2020-02-03 14:01
This seems a duplicate of https://github.com/ultralisp/ultralisp/issues/39 issue and was already fixed in pull https://github.com/ultralisp/ultralisp/pull/41

Could you please attach a screenshot of requested permissions?

**Comment by eschulte** [comment] 2020-02-05 01:37
<img width="538" alt="Screen Shot 2020-02-04 at 8 36 05 PM" src="https://user-images.githubusercontent.com/13414/73803187-069b7180-478e-11ea-886d-bd7941045b2f.png">

**Comment by svetlyak40wt** [comment] 2020-02-05 05:50
I see this url when authorizing at the GItHub:

https://github.com/login/oauth/authorize?client_id=f280a8af7d37e25826af&scope=public_repo%20user%3Aemail&redirect_uri=https%3A%2F%2Fultralisp.org%2Flogin%3Fretpath%3Dhttps%253A%252F%252Fultralisp.org%252Fgithub%26service%3Dgithub

Requested scope is: `public_repo user:email`.

Seems it is really gives a write access to everything. But ultralisp needs only a write access to webhooks.

Probably, changing `public_repo` to `write:repo_hook` will help here. I only need to check that this scope does not allow service to read list of private repositories.

<img width="696" alt="Screen Shot 2020-02-05 at 08 47 42" src="https://user-images.githubusercontent.com/24827/73814564-865c2700-47f4-11ea-86ff-1affc527a2bd.png">

**Comment by Hexstream** [comment] 2020-02-21 03:23
I just got this same write permissions request too, it's pretty scary.
`admin:repo_hook` seems promising.

**Comment by svetlyak40wt** [comment] 2020-02-22 21:07
Guys!

I've released a new version with a fix.

Now Ultralisp requests for two scopes: `admin:repo_hook` and `read:org`:

<img width="506" alt="Screenshot 2020-02-22 at 23 54 49" src="https://user-images.githubusercontent.com/24827/75099253-7c963a00-55d0-11ea-85be-5b4479a16eec.png">

**Closed** 2020-02-22 21:08 UTC
Labels: auth, bug

**Comment by Hexstream** [comment] 2020-02-22 22:29
Kickass! You rock!

Regarding your screenshot, users will note that they do *not* need to grant access to any of their organizations if not desired.
