### ISSUE TITLE
Project mmontone/ten does not get added

### ISSUE THREAD

**Issue by mmontone** [ultralisp/ultralisp#71] opened 2020-04-13 17:04 UTC
Hello.

I've tried to add this project several times: https://github.com/mmontone/ten

Ultralisp says it will check it, but then it doesn't add the package to Ultralisp.

Can someone manually add the project?

Thanks!

Mariano

**Comment by svetlyak40wt** [comment] 2020-04-18 15:42
I have to investigate the reason.

**Comment by svetlyak40wt** [comment] 2020-04-18 16:13
I see in the log, there was an error `System "ten" not found.`

The project was disabled automatically.

Try to open https://ultralisp.org/projects/mmontone/ten page and click this knob to turn it on again and reschedule the check:

<img width="554" alt="Screenshot 2020-04-18 at 19 11 52" src="https://user-images.githubusercontent.com/24827/79642877-9c994280-81a8-11ea-9865-55250579fef1.png">

**Comment by svetlyak40wt** [comment] 2020-04-18 16:14
By the way, may be this error was caused by the uninterned symbol in system's definition:

```
(asdf:defsystem #:ten
  :description "Template System for Common Lisp"
  ...
```

It is better to replace system's name with string `"ten"`. This is a recommended way to refer to ASDF systems.

**Comment by mmontone** [comment] 2020-04-18 16:28
Thanks for looking at this!

I've removed the uninterned symbol.

I've clicked the switch, but it didn't do anything, it did not turn green. Although it says Ten addition is scheduled.

![imagen](https://user-images.githubusercontent.com/436110/79643238-6e037380-8178-11ea-9d89-7b9b3c580369.png)

**Comment by Hexstream** [comment] 2020-04-18 16:40
I always use uninterned symbols like this (although maybe I shouldn't) and I successfully added tons of my projects to Ultralisp, so clearly this is not the problem here...

**Comment by svetlyak40wt** [comment] 2020-04-18 20:16
I found the problem!

It is because [ten.examples.asd](https://github.com/mmontone/ten/blob/master/ten.examples.asd) refers to the "ten" system, but quickdist unable to load it:

```
<ERROR> [19:46:06] ultralisp/pipeline/checking checking.lisp (update-check-as-failed) -
  Check failed, disabling project ULTRALISP/MODELS/PROJECT:PROJECT: #<ULTRALISP/MODELS/PROJECT:PROJECT GITHUB name=mmontone/ten enabled=NIL>
  ULTRALISP/PIPELINE/CHECKING::TRACEBACK: "Date/time: 2020-04-18-19:46!
An unhandled error condition has been signalled: System \"ten\" not found


Backtrace for: #<SB-THREAD:THREAD \"main thread\" RUNNING {10005984C3}>
0: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE-TO-STREAM #<SB-IMPL::CHARACTER-STRING-OSTREAM {100B1FA483}>)
1: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE #<QUICKLISP-CLIENT:SYSTEM-NOT-FOUND {100B1FA313}> :OUTPUT NIL :IF-EXISTS :APPEND :VERBOSE NIL)
2: (ULTRALISP/UTILS:GET-TRACEBACK #<QUICKLISP-CLIENT:SYSTEM-NOT-FOUND {100B1FA313}>)
3: ((FLET \"H0\" :IN ULTRALISP/PIPELINE/CHECKING:PERFORM) #<QUICKLISP-CLIENT:SYSTEM-NOT-FOUND {100B1FA313}>)
4: (SB-KERNEL::%SIGNAL #<QUICKLISP-CLIENT:SYSTEM-NOT-FOUND {100B1FA313}>)
5: (CERROR \"Try again\" QUICKLISP-CLIENT:SYSTEM-NOT-FOUND :NAME \"ten\")
6: ((LABELS QUICKLISP-CLIENT::RECURSE :IN QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY) \"ten\")
7: (QL-DIST::CALL-WITH-CONSISTENT-DISTS #<CLOSURE (LAMBDA NIL :IN QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY) {100B1DFDEB}>)
8: (QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY \"ten\")
9: (QUICKLISP-CLIENT::AUTOLOAD-SYSTEM-AND-DEPENDENCIES \"ten\" :PROMPT NIL)
10: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION (T T)) #<unused argument> #<CLOSURE (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {100B1DF76B}>) [fast-method]
11: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION :AROUND (QL-IMPL:SBCL T)) #<QL-IMPL:SBCL {1001DABC23}> #<CLOSURE (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {100B1DF76B}>) [fast-method]
12: ((:METHOD QUICKLISP-CLIENT:QUICKLOAD (T)) \"ten\" :PROMPT NIL :SILENT NIL :VERBOSE NIL) [fast-method]
13: (QL-DIST::CALL-WITH-CONSISTENT-DISTS #<CLOSURE (LAMBDA NIL :IN QUICKLISP-CLIENT:QUICKLOAD) {100B1C3E0B}>)
14: (QUICKDIST::GET-SYSTEMS #P\"/tmp/checker/mmontone-ten/ten.examples.asd\")
15: (QUICKDIST:MAKE-SYSTEMS-INFO #P\"/tmp/checker/mmontone-ten/\" :IGNORE-FILENAME-P #<CLOSURE (LAMBDA (&REST SB-IMPL::ARGUMENTS) :IN CONSTANTLY) {100AF56FFB}> :IGNORE-DEPENDENCY-P NIL)
16: (ULTRALISP/PIPELINE/CHECKING::COLLECT-SYSTEMS #P\"/tmp/checker/mmontone-ten/\")
17: (ULTRALISP/PIPELINE/CHECKING:PERFORM #<ULTRALISP/MODELS/CHECK:ADDED-PROJECT-CHECK mmontone/ten> :FORCE NIL)
```

**Comment by svetlyak40wt** [comment] 2020-04-18 20:38
I'll do further investigation and come back tomorrow.

**Comment by svetlyak40wt** [comment] 2020-04-18 21:46
Good news, everyone!

I wasn't able to sleep until fix this problem.

The issue was fixed with this commit: https://github.com/ultralisp/ultralisp/commit/89532c0ac63526c5af2fe7a872cdfaf8ee438377

<img width="638" alt="Screenshot 2020-04-19 at 00 42 44" src="https://user-images.githubusercontent.com/24827/79671990-c36e6d80-81d6-11ea-8409-987b3d764f7f.png">

**Closed by svetlyak40wt** 2020-04-18 21:46 UTC
Labels: bug

**Comment by mmontone** [comment] 2020-04-18 21:51
Amazing! Thanks!

And sorry for disturbing your sleep :)
